[build]
   publish = "." # Change to your actual build directory
  functions = ".netlify/v1/functions" # Path to functions folder

[dev]
  command = "npm run dev" # Change to your actual development server command
  port = 8888 # You can specify your local dev port

[build.environment]
  NODE_VERSION = "20.15.1"  # Updated to match your Node.js version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200